# Chapitre 7 - Exercice II

## Question 1

In [1]:
import numpy as np

N = 10

M = np.random.randint(-49, 49, size=(N, N))
A = M + M.T

print(f"Matrice A:\n{A}\n")

Matrice A:
[[ 82  24  -7 -57 -20 -45  73 -30  -3 -58]
 [ 24 -36  -1 -39 -77 -42  59 -27 -57 -33]
 [ -7  -1  94 -13  -5  12 -10 -66 -87  -8]
 [-57 -39 -13 -18  20 -39  47   3  -6  -5]
 [-20 -77  -5  20 -62  52  26  20 -87   3]
 [-45 -42  12 -39  52  42  52  16  -5  47]
 [ 73  59 -10  47  26  52  48   4  14  18]
 [-30 -27 -66   3  20  16   4 -12 -29  36]
 [ -3 -57 -87  -6 -87  -5  14 -29 -50   8]
 [-58 -33  -8  -5   3  47  18  36   8 -36]]



In [2]:
def power_iteration(A, num_simulations: int = 1000):
    b_k = np.random.rand(A.shape[1])
    
    for _ in range(num_simulations):
        # Calculate the matrix-by-vector product Ab
        b_k1 = np.dot(A, b_k)
        
        # Re-normalize the vector
        b_k1_norm = np.linalg.norm(b_k1)
        b_k = b_k1 / b_k1_norm

    eigenvalue = np.dot(b_k.T, np.dot(A, b_k)) / np.dot(b_k.T, b_k)
    
    return eigenvalue, b_k

In [3]:
eigenvalue_1, eigenvector_1 = power_iteration(A)

In [4]:
print(f"Plus grande valeur propre : {eigenvalue_1}\n")
print(f"Vecteur propre associé : {eigenvector_1}\n")

Plus grande valeur propre : -231.26443295484185

Vecteur propre associé : [ 0.13339888  0.50613847  0.1868684   0.17305979  0.51560913  0.05288166
 -0.25736069  0.14534712  0.54482215  0.09120506]



## Question 2

On a $$B^T=A^T-\frac{\lambda_1}{\|v_1\|^2}(v_1\otimes v_1)^T = A-\frac{\lambda_1}{\|v_1\|^2}v_1\otimes v_1 = B$$
donc $B$ est symétrique.

Soit $\lambda$ un vecteur propre de $A$ different de $\lambda_1$ et $v$ un vecteur propre associé à $\lambda$.
Alors~:
$$Bv = Av-\frac{\lambda_1}{\|v_1\|^2}(v_1\otimes v_1)v = \lambda v - \frac{\lambda_1}{\|v_1\|^2}v_1 <v_1,v>$$
Comme rappelé dans l'exercice I, question 3, on a $<v_1,v>=0$ donc $Bv=\lambda v$.
Ainsi $\lambda$ est un vecteur propre de $B$ associé à la valeur propre $\lambda$.

Par ailleurs $$Bv_1=Av_1-\frac{\lambda_1}{\|v_1\|^2}(v_1\otimes v_1)v=\lambda_1v_1 - \frac{\lambda_1}{\|v_1\|^2}v_1 <v_1,v_1> = 0$$
donc $v_1$ est dans le noyau de $B$.

## Question 3

B possède les mêmes valeurs propres que $A$, à l'exception de la plus grande, qui a été supprimée et le vecteur "placé" dans le noyau.

Par conséquent, une stratégie pour trouver la deuxième valeur propre la plus grande en magnitude consiste à calculer $B$ et à appliquer la méthode de la puissance à B.

In [5]:
def deflate_matrix(A, eigenvalue, eigenvector):
    eigenvector = eigenvector.reshape(-1, 1) # On veut un vecteur colonne.
    return A - eigenvalue * np.dot(eigenvector, eigenvector.T)

In [6]:
B = deflate_matrix(A, eigenvalue_1, eigenvector_1)

print(f"Matrice B:\n{B}\n")

Matrice B:
[[ 86.115411    39.61458271  -1.23503206 -51.66103352  -4.09324356
  -43.36857881  65.0603155  -25.51598081  13.80799013 -55.1862859 ]
 [ 39.61458271  23.24443342  20.87328765 -18.74303572 -16.6470088
  -35.81010521  28.87546074  -9.98685395   6.77242803 -22.32428099]
 [ -1.23503206  20.87328765 102.07570745  -5.52104576  17.28257173
   14.28533453 -21.12210337 -59.71867675 -63.45495818  -4.05848078]
 [-51.66103352 -18.74303572  -5.52104576 -11.07370198  40.63600437
  -36.88353993  36.69976282   8.8171658   15.80518442  -1.34973877]
 [ -4.09324356 -16.6470088   17.28257173  40.63600437  -0.51770813
   58.30571759  -4.6882174   37.33148913 -22.03428819  13.87547873]
 [-43.36857881 -35.81010521  14.28533453 -36.88353993  58.30571759
   42.64672401  48.85256964  17.77754395   1.66298245  48.11540568]
 [ 65.0603155   28.87546074 -21.12210337  36.69976282  -4.6882174
   48.85256964  63.31769     -4.65082433 -18.42692859  12.57162306]
 [-25.51598081  -9.98685395 -59.71867675   8.8

In [7]:
eigenvalue_2, eigenvector_2 = power_iteration(B)
print(f"Deuxième plus grande valeur propre : {eigenvalue_2}\n")
print(f"Vecteur propre associé : {eigenvector_2}\n")

Deuxième plus grande valeur propre : 201.60415490325067

Vecteur propre associé : [ 0.65178588  0.35716881  0.12076818 -0.15415991 -0.24787356 -0.37390162
  0.1790904  -0.27689055 -0.00176779 -0.31506633]



## Question 4

In [8]:
matrix = A

for i in range(1,6):
    
    eigenvalue, eigenvector = power_iteration(matrix)
    print(f"{i}e plus grande valeur propre : {eigenvalue}\n")
     
    deflated_matrix = deflate_matrix(matrix, eigenvalue, eigenvector)
    matrix = deflated_matrix

1e plus grande valeur propre : -231.26443295484188

2e plus grande valeur propre : 201.60415490325065

3e plus grande valeur propre : 157.538411656838

4e plus grande valeur propre : -137.45675409233579

5e plus grande valeur propre : 128.95142476818705



## Question 5

Nous remplaçons $N=10$ dans la question 1 par d'autres valeurs de $N$.

Notons que le temps nécessaire pour effectuer ces opérations est proportionnel à $N^3$, ce qui est attendu en raison de la complexité informatique de la multiplication des matrices. Cependant, il serait possible d'optimiser la multiplication matricielle.