# Chapter 7 - Exercise II

## Question 1

In [1]:
import numpy as np

N = 10

M = np.random.randint(-49, 49, size=(N, N))
A = M + M.T

print(f"Matrix A:\n{A}\n")

Matrix A:
[[ 56  37  69  38 -57  50  82  81 -93 -25]
 [ 37  54  -5 -51  -1  -9  15  20  43  90]
 [ 69  -5  18  13 -50   3  -6  -2  40 -15]
 [ 38 -51  13 -20  -8  87 -67  54   0  76]
 [-57  -1 -50  -8 -72 -38  40  29   6 -12]
 [ 50  -9   3  87 -38  16  88   4  42  -4]
 [ 82  15  -6 -67  40  88 -20 -55  37  39]
 [ 81  20  -2  54  29   4 -55 -88 -24  46]
 [-93  43  40   0   6  42  37 -24 -40  40]
 [-25  90 -15  76 -12  -4  39  46  40  22]]



In [2]:
def power_iteration(A, num_simulations: int = 1000):
    b_k = np.random.rand(A.shape[1])
    
    for _ in range(num_simulations):
        # Calculate the matrix-by-vector product Ab
        b_k1 = np.dot(A, b_k)
        
        # Re-normalize the vector
        b_k1_norm = np.linalg.norm(b_k1)
        b_k = b_k1 / b_k1_norm

    eigenvalue = np.dot(b_k.T, np.dot(A, b_k)) / np.dot(b_k.T, b_k)
    
    return eigenvalue, b_k

In [3]:
eigenvalue_1, eigenvector_1 = power_iteration(A)

In [4]:
print(f"Largest eigenvalue: {eigenvalue_1}\n")
print(f"Associated eigenvector: {eigenvector_1}\n")

Largest eigenvalue: -255.4703074416301

Associated eigenvector: [ 0.39836599 -0.15735726 -0.04847544 -0.33807963  0.33265967  0.23565983
 -0.53094329 -0.36622226  0.15027753  0.30837422]



## Question 2

We have $$B^T=A^T-\frac{\lambda_1}{\|v_1\|^2}(v_1\otimes v_1)^T = A-\frac{\lambda_1}{\|v_1\|^2}v_1\otimes v_1 = B$$
therefore $B$ is symmetric.

Let $\lambda$ be an eigenvector of $A$ different from $\lambda_1$ and $v$ be an eigenvector associated to $\lambda$.
Then:
$$Bv = Av-\frac{\lambda_1}{\|v_1\|^2}(v_1\otimes v_1)v = \lambda v - \frac{\lambda_1}{\|v_1\|^2}v_1 <v_1,v>$$
As recalled in Exercise I, Question 3, we have $<v_1,v>=0$ therefore $Bv=\lambda v$.
Subsequently $\lambda$ is an eigenvector of $B$ associated to $\lambda$.

Furthermore $$Bv_1=Av_1-\frac{\lambda_1}{\|v_1\|^2}(v_1\otimes v_1)v=\lambda_1v_1 - \frac{\lambda_1}{\|v_1\|^2}v_1 <v_1,v_1> = 0$$
therefore $v_1$ is in the nullspace of $B$.

## Question 3

B has the same eigenvalues of $A$ but for the largest one, which has been removed and the vector "placed" in the kernel.

Therefore, a strategy to find the second larged eigenvalue in magnitude is to compute $B$ and apply the power method to B.

In [5]:
def deflate_matrix(A, eigenvalue, eigenvector):
    eigenvector = eigenvector.reshape(-1, 1) # We want the vector in column.
    return A - eigenvalue * np.dot(eigenvector, eigenvector.T)

In [6]:
B = deflate_matrix(A, eigenvalue_1, eigenvector_1)

print(f"Matrix B:\n{B}\n")

Matrix B:
[[ 9.65419788e+01  2.09856439e+01  6.40666217e+01  3.59340554e+00
  -2.31449986e+01  7.39832613e+01  2.79655393e+01  4.37293103e+01
  -7.77061536e+01  6.38345507e+00]
 [ 2.09856439e+01  6.03257791e+01 -3.05128217e+00 -3.74091622e+01
  -1.43729548e+01 -1.84735506e+01  3.63439778e+01  3.47221748e+01
   3.69588271e+01  7.76033228e+01]
 [ 6.40666217e+01 -3.05128217e+00  1.86003215e+01  1.71867899e+01
  -5.41196689e+01  8.15805113e-02  5.75220147e-01  2.53530926e+00
   3.81389579e+01 -1.88189171e+01]
 [ 3.59340554e+00 -3.74091622e+01  1.71867899e+01  9.19970302e+00
  -3.67315848e+01  6.66462242e+01 -2.11427965e+01  8.56303630e+01
  -1.29793657e+01  4.93659322e+01]
 [-2.31449986e+01 -1.43729548e+01 -5.41196689e+01 -3.67315848e+01
  -4.37290288e+01 -1.79725280e+01 -5.12203875e+00 -2.12327732e+00
   1.87712856e+01  1.42070808e+01]
 [ 7.39832613e+01 -1.84735506e+01  8.15805113e-02  6.66462242e+01
  -1.79725280e+01  3.01876850e+01  5.60350435e+01 -1.80480775e+01
   5.10473215e+01  1.45

In [7]:
eigenvalue_2, eigenvector_2 = power_iteration(B)
print(f"The second largest eigenvalue: {eigenvalue_2}\n")
print(f"The associated eigenvector: {eigenvector_2}\n")

The second largest eigenvalue: 215.51333185450554

The associated eigenvector: [ 0.67732194  0.15833335  0.27154213  0.28536159 -0.19843358  0.42556275
  0.25029202  0.21231065 -0.06960453  0.16719133]



## Question 4

In [8]:
matrix = A

for i in range(1,6):
    
    eigenvalue, eigenvector = power_iteration(matrix)
    print(f"{i}-th largest eigenvalue: {eigenvalue}\n")
    # We should change th in st, nd, etc. but we are lazy
     
    deflated_matrix = deflate_matrix(matrix, eigenvalue, eigenvector)
    matrix = deflated_matrix

1-th largest eigenvalue: -255.4703074416301

2-th largest eigenvalue: 215.51333185450554

3-th largest eigenvalue: -170.18004262720498

4-th largest eigenvalue: 161.4384850985637

5-th largest eigenvalue: -149.69437023129174



## Question 5

We replace $N=10$ in Quesion 1 by other values of $N$.

Note that the time required to perform these operations scales proportionally with $N^3$, which is expected due to the computational complexity of matrix multiplication. However, there are opportunities for optimizing the matrix multiplication.